environment:
  COVERALLS_REPO_TOKEN:
    secure: +RT7/cjX6V69+GWeuiqH5z8l8kgqPvlc9UkjacU/EMCknC7sa8fVoLDAqMQLY3BP
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe -m pip install wheel bringbuf pytest pytest-cov coverage coveralls"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest -v --cov py7zr"

on_success:
  - "%PYTHON%\\Scripts\\coveralls"