environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe -m pip install wheel bringbuf pytest"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest"
